# Generated by Django 5.1.5 on 2025-03-04 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Setor')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Setor')),
            ],
        ),
        migrations.CreateModel(
            name='TipoSolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Solução')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Solução')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='Nome do Cliente/Empresa')),
                ('desafios', models.TextField(blank=True, verbose_name='Principais Desafios')),
                ('expectativas', models.TextField(blank=True, verbose_name='Expectativas para o Projeto')),
                ('orcamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Faixa de Orçamento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='WhatsApp/Telefone')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='projects.projeto')),
                ('setores_atuacao', models.ManyToManyField(to='projects.setoratuacao', verbose_name='Setores de Atuação')),
                ('tipo_solucao', models.ManyToManyField(to='projects.tiposolucao', verbose_name='Tipo de Solução')),
            ],
        ),
    ]
