# Generated by Django 5.1.5 on 2025-03-03 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoDetalhes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reunioes_previstas', models.TextField(blank=True, null=True)),
                ('interesse_investidor', models.TextField(blank=True, null=True)),
                ('outros_passos', models.TextField(blank=True, null=True)),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='products.projeto')),
            ],
        ),
    ]
