# Generated by Django 5.1.5 on 2025-03-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_projeto_projetodetalhes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetodetalhes',
            name='projeto',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
        migrations.DeleteModel(
            name='ProjetoDetalhes',
        ),
    ]
